### PR TITLE
development method hasOne

### PR DESCRIPTION
**Pull request by guivms**
Method to include the mapping of a simple class as an attribute.

### CODE REVIEW

**Comment by HennerM** [comment]
How is `hasOne()` different from `belongsTo()`?

**Comment by guivms** [comment]
Sorry about that, I just checked and realize they are the same. I made a confusion because of the syntax "Belongsto" and I didn't found any example or documentation more specific.

Why not add this situation inside hasmany? As we did.

**Comment by HennerM** [comment]
What do you mean by adding this situation into hasMany?

**Comment by guivms** [comment]
When the relation is one for one as belongsto do.

**Comment by HennerM** [comment]
I am still not sure what you mean.
Is there something left you want me to do?

**Comment by guivms** [comment]
There was an error of misinterpretation of the "belongto". You do not have to do anything else.

**Comment by hpawe01** [comment]
@HennerM, @guivms, @safo6m : Sorry, to comment on an closed pull request, but I ran into an issue where I would need the `HasOne` annotation.

`HasOne` is not the same as `BelongsTo`, because it is its reverse, like `HasMany`:
* 1 to n: `BelongsTo` => `HasMany`
* 1 to 1: `BelongsTo` => `HasOne`

When you use `BelongsTo` for both models (`BelongsTo` => `BelongsTo`), you get a circular dependency and a warning from Angular: `WARNING in Circular dependency detected`. This is because `BelongsTo` creates a real attribute on the model, whereas `HasMany` creates a pseudo-attribute. `HasOne` should do the same except returning an object and not a list.

Is this understandable or do I miss something?

Cheers,
Friedrich

**Comment by guivms** [comment]
Yes man

That's what I meant.

**Comment by baudday** [comment]
I know this was closed, but yes, there is a very big difference between `HasOne` and `BelongsToOne`.  Mainly, which table the foreign key lies on. If you have a `Package` entity which `BelongsToOne` `Sender` then `Package` will have a `sender_id`. If you have a `Package` which `HasOne` `Sender` then the `Sender` will have a `package_id`. This library not being able to handle the latter scenario is actually causing me much grief.

**Pull request closed without merging**
