### PR TITLE
[BUGFIX] #244 Fix removing belongsTo relations

### PR DESCRIPTION
**Pull request by frans-beech-it**

### CODE REVIEW

**Comment by frans-beech-it** [comment]
related to #148

**Comment by n2ygk** [comment]
@frans-beech-it I am experiencing this issue as well. I have what I think is a very common use case in which the parent model has an _optional_ singular child relationship. My use case is that I add a relationship and then want to remove it which I do by setting relationship to null. The resulting PATCH payload leaves it out rather than setting it to `"rel_name": null` per the [JSONAPI spec](https://jsonapi.org/format/#crud-updating-to-one-relationships)

I'm guessing this PR is because progress stalled on #148?

**Comment by fsaris** [comment]
I'm not sure if #148 is still relevant. But my pr resolves this issue. You can try is in your own project by pasting the 2 methods touched in this PR in your own datastore service.

Will try to add some tests to this soon so hopefully this can be merged.

**Comment by n2ygk** [comment]
> I'm not sure if #148 is still relevant. But my pr resolves this issue. You can try is in your own project by pasting the 2 methods touched in this PR in your own datastore service.
> 
> Will try to add some tests to this soon so hopefully this can be merged.

@fsaris Yep, grabbed `getRelationships` and `updateRelationships` and it works great. Thanks!

**Comment by n2ygk** [comment]
@fsaris @frans-beech-it Any progress on merging this?

**Comment by bosk59** [comment]
Waiting for a merge too....

**Comment by frans-beech-it** [comment]
@HennerM @hpawe01 what is needed to get this merged?

**Comment by hpawe01** [comment]
> @HennerM @hpawe01 what is needed to get this merged?

I don't have merge permissions, so I guess you meant only @HennerM?

**Comment by HennerM** [comment]
I am afraid I can't maintain this repo anymore. It would be best if you could talk to @ghidoz about transfering ownership.

**Comment by fsaris** [comment]
@HennerM tnx for merging

**Comment by fsaris** [comment]
> I am afraid I can't maintain this repo anymore. It would be best if you could talk to @ghidoz about transfering ownership.

Please let me know if you need someone to help here

**Comment by ghidoz** [comment]
> > I am afraid I can't maintain this repo anymore. It would be best if you could talk to @ghidoz about transfering ownership.
> 
> Please let me know if you need someone to help here

@fsaris sorry, I missed the mention. Are you still interested in managing the project? I can add you as a collaborator

**Comment by fsaris** [comment]
> @fsaris sorry, I missed the mention. Are you still interested in managing the project? I can add you as a collaborator

Sounds good 👍🏼

**Pull request merged**
