### PR TITLE
Add a way to remove To-One relationships

### PR DESCRIPTION
**Pull request by HennerM**

### CODE REVIEW

**Comment by safo6m** [comment]
What is the logic behind this one?
What is a use case when the lib would have to take care of deleting relationships?

If I understood correctly, you want to delete one relationship from a model. In that case a better solution would be deleting the relationship model itself.

**Comment by RicardoNeves** [comment]
@safo6m 
I might be wrong but this might be related with the following issue.
Let's say you have a tree  structure of nodes. Each node can have a parent node and can have multiple children nodes.
Let's say you have a "node A" that is the parent of "node B".
How do you remove the parent relationship from "node B"?

I didn't had time to test this branch yet, but I'm having this kind of issue in one of my projects right now.

**Comment by frans-beech-it** [comment]
Would be great if this could get in :smiley: 

Removing existing relations is currently not possible and that's a real missing feature

**Comment by jevanlingen** [comment]
PR is not complete (anymore). I added the changes to my project, so I could make use of this feature. I needed to check if the relationshipModel did exist in the `updateRelationships` function as well ([line 436](https://github.com/ghidoz/angular2-jsonapi/blob/cf3e232af8cc76ed12d0b7ea64fa1cda57556a38/src/services/json-api-datastore.service.ts#L436)).

**Pull request closed without merging**
