### PR TITLE
Fix#239 cyclic hasmany

### LINKED ISSUE #239: Cyclic/nested HasMany relationships are not extracted
I have a sample repo demonstrating this issue: https://github.com/magneticflux-/angular2-jsonapi-issue-reproduction

Simply clone it and run `ng test --no-watch` and one test should fail. I believe I have valid JSON:API data and correct model classes.

I expect `thing_1.categories[0]` to be `category_1`, and this is correct. However, I also expect `category_1.members[0]` to be `thing_1`, but the array is empty instead.

### PR DESCRIPTION
**Pull request by magneticflux-**
Doesn't fix #239 yet, but it demonstrates the issue.

### CODE REVIEW

**Comment by magneticflux-** [comment]
@safo6m Would you accept a PR refactoring the project into the standard Angular CLI [library format](https://angular.io/guide/creating-libraries)? I think it would help with testing and deployment, and make it easier to update going forwards.

**Comment by safo6m** [comment]
> @safo6m Would you accept a PR refactoring the project into the standard Angular CLI [library format](https://angular.io/guide/creating-libraries)? I think it would help with testing and deployment, and make it easier to update going forwards.

@magneticflux- 
of course, that would be fantastic

**Comment by magneticflux-** [comment]
@safo6m I think this fixes it. Can you release another beta with these changes soon?

**Comment by safo6m** [comment]
> @safo6m This fixes the issue in my own situation. Can you release another beta with these changes soon?

v8.2.1-beta released

**Pull request merged**
